apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: your-docker-registry/payment-service:latest  # Docker Hub'daki image'ı kullanıyoruz
        ports:
        - containerPort: 5000  # Mikroservisin kullandığı port
        env:
        - name: DATABASE_URL
          value: "mongodb://mongo:27017/payments"  # Örnek MongoDB bağlantısı, kendi veritabanı bilgilerinle değiştir.
        - name: FLASK_ENV
          value: "production"
        - name: SECRET_KEY
          value: "mysecretkey"  # Flask için secret key
        resources:
          requests:
            memory: "512Mi"  # Minimum bellek isteği
            cpu: "250m"      # Minimum CPU isteği
          limits:
            memory: "1Gi"    # Maksimum bellek limiti
            cpu: "500m"      # Maksimum CPU limiti
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
